version: '3'
services:

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            migrations: true
            host: db
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
    ports:
      - 4466:4466

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    restart: always
    build:
      context: frontend
    ports:
      - 80:80

  yoga-server:
    restart: always
    build:
      context: yoga-server
    ports:
      - 4000:4000

volumes:
  postgres_data:
