version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: managementApiSecret
        port: 4466
        databases:
          default:
            connector: postgres
            migrations: true
            host: db
            port: 5432
            user: postgres
            password: prisma
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
