kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  namespace: abis
  labels:
    stage: production
    name: database
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi